defaults: &defaults
  encoding: utf8
  adapter: postgresql
  host: localhost

production:
  url: <%= ENV['DATABASE_URL'] %>
  database: hutt
  pool: 5
  timeout: 5000

development:
  <<: *defaults
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD']%>
  database: <%= ENV['DB_DATABASE']%>

test:
  <<: *defaults
