defaults: &defaults
  encoding: utf8
  adapter: mysql2
  host: localhost
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD']%>
  database: <%= ENV['DB_DATABASE']%>

production:
  <<: *defaults

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults
